// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmbvsbzjwoshuxvzpiyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptYnZzYnpqd29zaHV4dnpwaXliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzNTY0MzksImV4cCI6MjA4OTkzMjQzOX0.M8VOElGVJcI5gETM4dW48JlyLpi3EzOFpYAXW7Gm2i0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});